name: Continuos Integration

on:
  push:
    branches:
      - feat/add-github-actions

jobs:
  continuos-integration:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8

      - name: Build with Maven
      - run: mvn package

